### ISSUE TITLE
Set up auth routes and pages

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#1]
### Description
We need a way to register, log in, and log out

### Tasks
- [x] Set up EF Core and Identity
- [x] Routes:
    + [x] /api/auth/register
    + [x] /api/auth/login
    + [x] /api/auth/logout
- [x] Pages:
    + [x] Register page
    + [x] Login page
    + [x] Log out functionality
- [x] Refactor code
