### ISSUE TITLE
FULL: Send verification emails

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#16]
### Tasks
- [x] Configure email provider
- [x] Configure Identity with `options.SignIn.RequireConfirmedAccount = true;`
- [x] Send registration confirmation emails
- [x] Update client to support email verification
    + [x] Display loading state when registering
    + [x] Display loading state when verifying email
