### ISSUE TITLE
Set up frontend

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#3]
### Description
Set up the frontend and ensure it can communicate with the backend.

### Tasks
- [x] Set up Vue with Vite
- [x] Libraries to include:
    + [x] Pinia
    + [x] Vue Router
    + [x] Vue Query
    + [x] Vue testing stuff
    + [x] ESLint
    + [x] Prettier
- [ ] Confirm that it can connect to the backend
