### ISSUE TITLE
API: Finance record endpoints

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#36]
## Description
This issue encompasses the work for finance records CRUD.

## Tasks
- [x] Create finance record
- [x] Get single finance record
- [x] Get paginated finance records
- [x] Update finance record
- [x] Delete finance record
