### ISSUE TITLE
API: Add sorting and filtering for finance records

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#39]
## Tasks
- [x] Add filtering by:
    + [x] Min / max amount
    + [x] Description
    + [x] Min / max happenedAt
    + [x] Type
- [x] Add bidirectional sorting by:
    + [x] Amount
    + [x] Happened at
