### ISSUE TITLE
FS: Rely on backend for password validation checks

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#40]
## Description
The logic for determining if a password is valid shouldn't live on both the frontend and backend.

## Tasks
- [x] Add endpoint to get password requirements
- [x] Update registration flow to validate password by querying the backend
- [x] Display password criteria in the UI

## Linked issues
#1
