### ISSUE TITLE
FE: Create toaster

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#41]
## Description
I want the ability to display toasts.

## Tasks
- [x] Create Toaster component
- [x] Create Toast component
- [x] Show toast when successfully creating / editing a finance record
