### ISSUE TITLE
FE: Display paginated finance records

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#44]
## Tasks
- [x] Create FinanceRecord UI
- [x] Display list of finance records
- [x] Use Vue Query
