### ISSUE TITLE
API+FE: Finance records stats

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#73]
## Tasks
- [x] Add endpoint to fetch stats for finance records
    - [x] Should support the same filter query parameters as the regular GET paginated endpoint
- [x] Display finance record stats

## Linked issues
#39
