### ISSUE TITLE
FULL: Account page

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#85]
## Description
Add a page for the user to view, update, and delete their account.

## Tasks
- [x] Add endpoint to reset password
- [x] Add endpoint to delete account
- [x] Add account page
