### ISSUE TITLE
FS: Finance record tags

### ISSUE THREAD

**Issue by Philosocode** [Philosocode/okane#98]
## Description
This issue encompasses the work required to associate tags with finance records.

## Tasks
- [x] Add endpoint to fetch user-created finance record tags
- [x] Can create / edit finance record with tags
- [x] Add page to manage tags
    + [ ] ~~Create tag~~ Decided not to implement this. You can already create tags via the create / edit finance record modal.
    + [ ] Rename tag
    + [ ] Delete tag
- [ ] Filter finance records by tags
